---
- name: MacOS | Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  become: false

- name: MacOS | Install basic system tools
  community.general.homebrew:
    name:
      - curl
      - git
      - fzf
    state: present
  become: false

- name: MacOS | Install Casks (Raycast, Docker, Ghostty)
  community.general.homebrew_cask:
    name:
      - raycast
      - docker
      - ghostty
    state: present
    accept_external_apps: true
  become: false
